version: '2'
services:
    acme-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/acme/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=acme
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
